// const input=document.getElementById("inp");
// //input=<input type="number" name="" id="inp">

// const result=document.getElementById("result");
// //result=<div id="result"></div><br>

// const submit=document.getElementById("submit");
// //submit=<button id="submit">Submit</button>

// //now we have to make a variable which hold the random value generated by the computer
// let computer_generated=Math.floor(Math.random);

// submit.addEventListener("click",() => {
//     let finalresult="";
//     if(computer_generated===input){
//     finalresult.textContent="Correct!"
//     }else if(computer_generated>input){
//     finalresult.textContent="Too Low!"
//     }else{
//     finalresult.textContent="Too high!"
//     }
//     result.textContent=finalresult;
// });


const input = document.getElementById("inp");
// input = <input type="number" name="" id="inp">

const result = document.getElementById("result");
// result = <div id="result"></div><br>

const submit = document.getElementById("submit");
// submit = <button id="submit">Submit</button>

// now we have to make a variable which hold the random value generated by the computer
let computer_generated = Math.floor(Math.random() * 100) + 1; // ✅ Fix: Math.random() not Math.random

submit.addEventListener("click", () => {
    let finalresult = "";

    const userGuess = Number(input.value); // ✅ Fix: Get number from input value

    if (computer_generated === userGuess) {
        finalresult = "Correct!";
    } else if (computer_generated > userGuess) {
        finalresult = "Too Low!";
    } else {
        finalresult = "Too High!";
    }

    result.textContent = finalresult; // ✅ Fix: You were trying to change `finalresult.textContent`, which is a string
});
